# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-release
sudo: true
cache: packages
os:
- osx
- linux
bioc_packages:
- GO.db
- org.Hs.eg.db

before_install:
- chmod +x installCytoscape.sh
- ./installCytoscape.sh
- pip install -r requirements.txt

install:
- Rscript travis_script.r

script:
- travis_wait R CMD build .
- travis_wait R CMD check *tar.gz --no-manual

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
